from pybricks.tools import wait
from pybricks.parameters import Button, Color, Direction, Port, Side, Stop
from distance_sensor import AndySensor

def MissionThree(robot:DriveBase, left_attachment_motor, right_attachment_motor, eyes: AndySensor):
    print("Mission Three")
    robot.settings(straight_speed=400)
    robot.straight(325)
    robot.turn(-45)
    robot.straight(135)
    robot.turn(-60)
    robot.turn(60)
    right_attachment_motor.run_time(-500,500,Stop.HOLD, False)
    left_attachment_motor.run_time(-500,500)
    robot.straight(-200)
    robot.straight(20)
    right_attachment_motor.run_time(900,800,Stop.HOLD, False)
    left_attachment_motor.run_time(900,800)
    robot.straight(20)
    robot.straight(-80)
    robot.turn(-50)
    robot.straight(250)
    robot.turn(65)
    robot.straight(100)
    right_attachment_motor.run_time(-500,500,Stop.HOLD, False)
    left_attachment_motor.run_time(-500,500)
    right_attachment_motor.run_time(900,800,Stop.HOLD, False)
    left_attachment_motor.run_time(900,800)
    robot.straight(-110)
    robot.turn(-50)
    robot.straight(160)
    robot.turn(85)
    robot.straight(100)
    robot.straight(-100)
    robot.turn(-90)
    robot.straight(-580)
    